.gitignore, .vscode/launch.json, .vscode/tasks.json, integrations/standalone/index.html, integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/tsconfig.json, integrations/standalone/vite.config.js, package.json, packages/editor/src/yaml-table.tsx
she is not yet a beauty, but she works
=> XIVY-11751 provide standalone integration

.gitignore, .prettierignore, build/Dockerfile, build/Jenkinsfile, build/unpublish-npm.sh, build/use-mirror-npm.sh, integrations/standalone/.eslintrc.js, integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/vscode/extension/package.json, integrations/vscode/extension/src/editor-provider.ts, integrations/vscode/webview/package.json, integrations/vscode/webview/vite.config.ts, lerna.json, package.json, packages/editor/.eslintrc.js, packages/editor/package.json, packages/editor/src/yaml-table.tsx, yarn.lock
- and push to https://npmjs-registry.ivyteam.io/
=> XIVY-11751 provide build pipeline

integrations/vscode/extension/src/editor-provider.ts, packages/editor/src/yaml-table.tsx
- do not error if last key/value pair gets deleted
=> XIVY-11751 fix: support multi config editors in vscode

packages/editor/src/yaml-table.tsx
=> XIVY-11751 group support

packages/editor/src/yaml-table.tsx
=> XIVY-11751 use parseDocument to preserve raw yaml structure

packages/editor/src/yaml-table.tsx
- preserve order when key is changed
=> XIVY-11751 fixes for vs code integration

packages/editor/src/yaml-table.tsx
now children can also be added to parent2 and parent3
=> XIVY-11751 remove title & fix broken parent nodes

integrations/standalone/package.json, lerna.json, packages/editor/package.json
Raise version to 11.2.2-SNAPSHOT
=> Raise version to 11.2.2-SNAPSHOT

package-lock.json, packages/new-editor/package.json, packages/new-editor/src/components/editor/Editor.css, packages/new-editor/src/components/editor/Editor.tsx, packages/new-editor/src/components/editor/data/Variable.ts, packages/new-editor/src/components/editor/variables/master/Variables.tsx
=> XIVY-11980 implement Variables component

package-lock.json, packages/new-editor/package.json, packages/new-editor/src/components/editor/Editor.css, packages/new-editor/src/components/editor/Editor.tsx, packages/new-editor/src/components/editor/data/Variable.ts, packages/new-editor/src/components/editor/variables/detail/Variable.tsx, packages/new-editor/src/components/editor/variables/master/Variables.tsx
=> XIVY-11980 implement VariableDetail component

packages/new-editor/src/components/editor/Editor.tsx, packages/new-editor/src/components/editor/variables/detail/Variable.tsx, packages/new-editor/src/components/editor/variables/master/Variables.tsx
=> XIVY-11980 implement variable selection

packages/new-editor/src/components/editor/Editor.css, packages/new-editor/src/components/editor/Editor.tsx, packages/new-editor/src/components/editor/control/Control.css, packages/new-editor/src/components/editor/control/Control.tsx, packages/new-editor/src/components/editor/variables/detail/Variable.tsx, packages/new-editor/src/components/editor/variables/master/Variables.tsx
- Buttons for adding and deleting variables are present but not functional
- Always show detail view
=> XIVY-11980 implement variables control

packages/new-editor/src/components/editor/variables/detail/Variable.tsx
Should they be ordered differently?
=> XIVY-11980 show description for values with children

packages/new-editor/src/components/editor/variables/master/Variables.tsx
Continuation of https://github.com/axonivy/config-editor-client/pull/44
=> XIVY-11980 implement variable add control

packages/new-editor/src/components/editor/control/Control.tsx, packages/new-editor/src/components/editor/data/Variable.ts, packages/new-editor/src/components/editor/variables/master/Variables.tsx
- rename indexes to path
- use Array instead of []
=> XIVY-11980 minor changes

packages/new-editor/src/components/editor/Editor.tsx
=> XIVY-11980 implement sidebar collapse

integrations/standalone/tsconfig.json, tsconfig.json
- So new-editor will be build with root npm run build script
=> Fix typescript references

integrations/standalone/vite.config.ts, packages/new-editor/src/components/editor/Editor.tsx, packages/new-editor/src/components/editor/data/Variable.test.ts, packages/new-editor/src/components/editor/data/Variable.ts, packages/new-editor/src/components/editor/variables/detail/EnumValues.tsx, packages/new-editor/src/components/editor/variables/detail/Metadata.tsx, packages/new-editor/src/components/editor/variables/detail/PossibleEnumValues.tsx, packages/new-editor/src/components/editor/variables/detail/Value.tsx, packages/new-editor/src/components/editor/variables/detail/Variable.tsx, packages/new-editor/src/components/editor/variables/master/Variables.tsx, packages/new-editor/src/data/data.test.ts, packages/new-editor/src/data/data.ts, packages/new-editor/src/data/table-data.test.ts, packages/new-editor/src/data/table-data.ts, packages/new-editor/src/types/config.ts, packages/new-editor/src/utils/table.test.ts, packages/new-editor/src/utils/table.ts, packages/new-editor/src/utils/tree.test.ts, packages/new-editor/src/utils/tree.ts
=> XIVY-11980 adjust variable detail to metadata

packages/new-editor/src/components/variables/master/VariablesMaster.tsx, packages/new-editor/src/utils/tree/tree-data.test.ts, packages/new-editor/src/utils/tree/tree-data.ts, packages/new-editor/src/utils/tree/tree.test.ts, packages/new-editor/src/utils/tree/tree.ts
=> XIVY-11980 implement variable search

integrations/standalone/src/index.tsx, integrations/standalone/src/url-helper.ts, packages/variable-editor/src/components/editor/Editor.tsx, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx
- Add options popup for theme switch
=> XIVY-14079 Add readonly mode

packages/variable-editor/src/components/variables/detail/VariablesDetail.tsx
Same as https://github.com/axonivy/config-editor-client/pull/83
=> XIVY-14079 focus name input of new variable > 11.3

packages/variable-editor/src/components/control/Control.tsx
Same as https://github.com/axonivy/config-editor-client/pull/87
=> Change control spacing > 11.3

build/Jenkinsfile
... as we do it in other repos.
=> run update axonivy next before building

build/Jenkinsfile, package-lock.json, packages/variable-editor/package.json
... as we do it in other repos
=> run update axonivy next before building & manual package lock fix

packages/variable-editor/src/VariableEditor.tsx, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx, packages/variable-editor/src/protocol/client-json-rpc.ts, packages/variable-editor/src/protocol/types.ts
Simply displaying the messages at the top for now.
=> XIVY-13802 get validation messages

packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts, packages/variable-editor/src/components/variables/master/ValidationMessagesRows.tsx, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx, packages/variable-editor/src/protocol/types.ts
=> XIVY-13802 show validation messages on row

packages/variable-editor/src/VariableEditor.tsx, packages/variable-editor/src/protocol/client-json-rpc.ts, packages/variable-editor/src/protocol/types.ts
Relevant core change: https://github.com/axonivy/core/pull/6095
=> XIVY-13802 update variables editor validation messages on change

packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts, packages/variable-editor/src/components/variables/master/ValidationMessagesRows.tsx, packages/variable-editor/src/components/variables/master/ValidationRow.css, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx
=> XIVY-13802 highlight rows with validation messages

package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/input/PasswordInput.tsx, packages/variable-editor/src/components/variables/data/variable-utils.test.ts, packages/variable-editor/src/components/variables/data/variable-utils.ts, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx
- icons shown in the tree of the variables editor adjust to the metadata type of the variable
- changed the icon in the password input to an eye
=> XIVY-14003 adjust icons to type

packages/variable-editor/src/components/detail/EmptyDetail.css, packages/variable-editor/src/components/detail/EmptyDetail.tsx, packages/variable-editor/src/components/editor/Editor.css, packages/variable-editor/src/components/editor/Editor.tsx, packages/variable-editor/src/components/variables/detail/VariablesDetail.tsx
=> XIVY-14003 beautify empty detail view

package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/detail/EmptyDetail.tsx
update internal dependencies for access to new icon
Old:
New:
=> XIVY-14003 new icon for empty detail view

.gitignore, packages/variable-editor/src/components/variables/data/test-utils/types.ts, packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx, packages/variable-editor/src/utils/tree/tree.test.ts, packages/variable-editor/src/utils/tree/tree.ts
Core change: https://github.com/axonivy/core/pull/6217
=> XIVY-14264 use key to match validation messages

integrations/standalone/tests/integration/variable-editor.spec.ts, integrations/standalone/tests/mock/variable-editor-detail.spec.ts, integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/VariableEditor.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.css, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx
functionality is identical as before for now, just sending the user through the dialog
=> XIVY-14357 add variable dialog

integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/AddVariableDialog.ts, integrations/standalone/tests/pageobjects/Combobox.ts, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/master/AddVariableDialog.css, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/utils/tree/tree.test.ts, packages/variable-editor/src/utils/tree/tree.ts
any known namespace can now be selected in the combobox
a new namespace can be input as well
added unittests for gathering all known namespaces
improved playwright test to check that known namespaces are present in the selection of the combobox
=> XIVY-14357 add options of all known namespaces

packages/variable-editor/src/VariableEditor.tsx
see https://github.com/axonivy/form-editor-client/pull/67
=> XIVY-14104 make data query key unique

packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts
=> XIVY-14357 do not allow dots in name

packages/variable-editor/src/components/variables/detail/Value.tsx, packages/variable-editor/src/components/variables/detail/VariablesDetail.tsx, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx
=> Move focus to value field after add new variable

packages/variable-editor/src/components/variables/data/metadata.test.ts, packages/variable-editor/src/components/variables/data/metadata.ts, packages/variable-editor/src/components/variables/data/variable.ts, packages/variable-editor/src/components/variables/detail/EnumValues.tsx, packages/variable-editor/src/components/variables/detail/Metadata.tsx, packages/variable-editor/src/components/variables/detail/Value.tsx, packages/variable-editor/src/components/variables/detail/VariablesDetail.tsx, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx, packages/variable-editor/src/utils/tree/tree-data.test.ts, packages/variable-editor/src/utils/tree/types.ts
remove abstraction of `TreeNode` attributes
remove abstraction of `Variable` attributes
=> refactor: remove abstraction of attributes

integrations/standalone/src/index.tsx, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.css, packages/variable-editor/src/protocol/client-json-rpc.ts
https://github.com/axonivy/ui-components/pull/150
=> XIVY-14729 Add websocket reconnect

integrations/standalone/tests/integration/variable-editor.spec.ts, integrations/standalone/tests/mock/variable-editor-detail.spec.ts, packages/variable-editor/src/components/variables/data/metadata.test.ts, packages/variable-editor/src/components/variables/data/metadata.ts, packages/variable-editor/src/components/variables/detail/Metadata.tsx
=> Label default variable metadata as 'Default'

package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/data/test-utils/test-utils.tsx, packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/components/variables/master/ValidationRow.test.ts, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, packages/variable-editor/src/context/AppContext.tsx, packages/variable-editor/src/context/useValidation.test.ts, packages/variable-editor/src/context/useValidation.ts, playwright/tests/integration/mock/variable-editor.spec.ts, playwright/tests/pageobjects/FieldMessage.ts
=> Add description to add dialog namespace

.vscode/launch.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/detail/DetailContent.tsx, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/context/AppContext.tsx, packages/variable-editor/src/utils/lambda/lambda.ts, playwright/tests/integration/mock/detail.spec.ts, playwright/variables-test-project/config/variables.yaml
=> XIVY-15332 Fix duplicated var removes it from the list

integrations/standalone/package.json, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/data/test-utils/test-utils.tsx, packages/variable-editor/src/components/variables/detail/DetailContent.test.ts, packages/variable-editor/src/components/variables/detail/DetailContent.tsx, playwright/tests/integration/mock/import.spec.ts
Make the metadata read only if the variable is found in the known variables of the required projects.
=> XIVY-14730 disable metadata of overwritten variables

packages/variable-editor/src/components/variables/detail/DetailContent.tsx, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/dialog/known-variables.test.ts, packages/variable-editor/src/components/variables/dialog/known-variables.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/mock/import.spec.ts, playwright/tests/pageobjects/AddVariableDialog.ts, playwright/tests/pageobjects/Button.ts, playwright/tests/pageobjects/VariableEditor.ts
When manually adding a variable that is present in a required project, the known variable is imported instead.
=> XIVY-15648 import when manually adding variable

integrations/standalone/package.json, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/utils/tree/tree.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/pageobjects/Table.ts
Cherry-Pick from https://github.com/axonivy/config-editor-client/pull/222/
=> XIVY-13545 Add Navigation via ArrowKey in Main-Table

packages/variable-editor/src/components/variables/master/VariablesMasterContent.css
master https://github.com/axonivy/config-editor-client/pull/231
=> XIVY-15022 Fix overflow > R12

integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, integrations/standalone/src/mock/variables-client-mock.ts, package-lock.json, package.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/dialog/AddDialog.test.ts, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterToolbar.tsx, packages/variable-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/mock/import.spec.ts, playwright/tests/integration/url-params.spec.ts, playwright/tests/pageobjects/AddVariableDialog.ts, playwright/tests/pageobjects/Details.ts, playwright/tests/pageobjects/OverwriteDialog.ts, playwright/tests/pageobjects/TextArea.ts, playwright/tests/pageobjects/VariableEditor.ts, playwright/tests/pageobjects/console-log.ts
Global:
- F1: Open help
- A: Add new variable (hold ctrl/cmd to keep it open)
- I: Import variable
- 1-3: jump focus (toolbar, main, inscription)
On Table:
- Delete: remove selected variable
=> XIVY-15022 Add shortcuts

integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, integrations/standalone/src/mock/variables-client-mock.ts, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/dialog/AddDialog.test.ts, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterToolbar.tsx, packages/variable-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/mock/import.spec.ts, playwright/tests/integration/url-params.spec.ts, playwright/tests/pageobjects/AddVariableDialog.ts, playwright/tests/pageobjects/Details.ts, playwright/tests/pageobjects/OverwriteDialog.ts, playwright/tests/pageobjects/TextArea.ts, playwright/tests/pageobjects/VariableEditor.ts, playwright/tests/pageobjects/console-log.ts
Global:
- F1: Open help
- A: Add new variable (hold alt to keep it open)
- I: Import variable
- 1-3: jump focus (toolbar, main, inscription)
On Table:
- Delete: remove selected variable
master: https://github.com/axonivy/config-editor-client/pull/229
=> XIVY-15022 Add shortcuts > R12

integrations/standalone/package.json, integrations/standalone/src/index.tsx, integrations/standalone/src/mock.tsx, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterToolbar.tsx
https://github.com/axonivy/config-editor-client/pull/233
=> XIVY-15631 Fix disable hotkeys > R12

packages/variable-editor/src/components/variables/detail/DetailContent.css
Similar to https://github.com/axonivy/dataclass-editor-client/pull/137
=> make detail scrollable > master

integrations/standalone/package.json, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/data/test-utils/test-utils.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterToolbar.tsx, packages/variable-editor/src/context/AppContext.tsx, playwright/tests/integration/mock/detail.spec.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/variable-editor.spec.ts, playwright/tests/pageobjects/Toolbar.ts, playwright/tests/pageobjects/VariableEditor.ts
master: https://github.com/axonivy/config-editor-client/pull/239
=> XIVY-15022 Undo / Redo > R12

integrations/standalone/package.json, package-lock.json, package.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/data/test-utils/test-utils.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterToolbar.tsx, packages/variable-editor/src/context/AppContext.tsx, playwright/tests/integration/mock/detail.spec.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/integration/variable-editor.spec.ts, playwright/tests/pageobjects/Toolbar.ts, playwright/tests/pageobjects/VariableEditor.ts
I will move the hook itself and it's tests to the ui-components, as it is more or less the same as in the form editor
And I will also add an undo/redo button I think
=> XIVY-15022 Undo / Redo

integrations/standalone/src/mock/meta.ts, packages/protocol/src/editor.ts
Protocol changed by https://github.com/axonivy/core/pull/7731
=> update protocol with polymorphic metadata > master

integrations/standalone/package.json, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/VariablesEditor.tsx, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterToolbar.tsx, packages/variable-editor/src/utils/hotkeys.ts, playwright/tests/integration/mock/editor.spec.ts
https://github.com/axonivy/config-editor-client/pull/277
=> Redo hotkey > R12

packages/variable-editor/src/components/variables/detail/DetailContent.test.ts, packages/variable-editor/src/components/variables/detail/DetailContent.tsx, playwright/tests/integration/mock/detail.spec.ts, playwright/tests/integration/mock/import.spec.ts, playwright/tests/integration/variable-editor.spec.ts, playwright/tests/pageobjects/Details.ts
Requested by Bruno.
In a big `variables.yaml`, you can easily get lost where the Variable you have selected is located exactly.
=> add namespace to detail view > master

packages/variable-editor/src/components/variables/detail/DetailContent.test.ts, packages/variable-editor/src/components/variables/detail/DetailContent.tsx, playwright/tests/integration/mock/detail.spec.ts, playwright/tests/integration/mock/import.spec.ts, playwright/tests/integration/variable-editor.spec.ts, playwright/tests/pageobjects/Details.ts
Requested by Bruno.
In a big `variables.yaml`, you can easily get lost where the Variable you have selected is located exactly.
=> add namespace to detail view > 12

integrations/standalone/package.json, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/vite.config.ts
https://github.com/axonivy/config-editor-client/pull/339
=> Move @axonivy packages to peer deps > R12

integrations/standalone/package.json, integrations/standalone/src/mock.tsx, integrations/standalone/src/mock/data.ts, integrations/standalone/src/mock/variables-client-mock.ts, package-lock.json, package.json, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, playwright/tests/integration/mock/editor-keyboard.spec.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/pageobjects/Table.ts, playwright/tests/pageobjects/VariableEditor.ts
- Set vindex attribute on role
- Setup possiblity to load more data on mock to get virtualized rows
master https://github.com/axonivy/config-editor-client/pull/444
=> XIVY-16222 Fix scroll in virtualized rows via arrow keys

packages/variable-editor/src/components/variables/data/metadata.ts, packages/variable-editor/src/components/variables/detail/DetailContent.tsx, packages/variable-editor/src/components/variables/detail/MetadataPart.tsx
feedback for: https://github.com/axonivy/config-editor-client/pull/448
=> XIVY-16265 I18n feedbacks

eslint.config.mjs, integrations/standalone/package.json, package-lock.json, package.json, packages/variable-editor/src/components/variables/data/test-utils/test-utils.tsx, playwright/tests/integration/mock/i18n.spec.ts, playwright/tests/pageobjects/VariableEditor.ts
- config cleanup
- playwright test
=>  XIVY-16265 I18n improve

integrations/standalone/src/index.css, packages/variable-editor/src/VariablesEditor.css
https://github.com/axonivy/form-editor/pull/498
=> Move ui-components/icons css to integration

integrations/standalone/package.json, package.json, packages/protocol/package.json, packages/variable-editor/package.json, playwright/package.json, playwright/playwright.config.ts
https://github.com/axonivy/variable-editor/pull/509
=> Scope all packages > R12

integrations/standalone/package.json, package-lock.json, package.json, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, playwright/tests/integration/mock/editor.spec.ts
[https://github.com/axonivy/dataclass-editor/pull/459](https://github.com/axonivy/dataclass-editor/pull/459)
=> XIVY-17023 Disable hotkey scope 'global' if dialog is open

integrations/standalone/package.json, package-lock.json, package.json, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx
https://1ivy.atlassian.net/browse/XIVY-16606
=> XIVY-1606 Streamline Dialog

integrations/standalone/package.json, package-lock.json, package.json, packages/variable-editor/src/components/variables/dialog/AddDialog.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx
https://github.com/axonivy/ui-components/pull/544
=> XIVY-16606 Apply basic dialog changes
