axonivy/variable-editor

build/Jenkinsfile
So it is easier to find out what was wrong if the build fails or is unstable
=> Only clean ws on success

packages/new-editor/src/components/editor/Editor.tsx, packages/new-editor/src/components/editor/variables/master/Variables.tsx
- The delete button is disabled if no variable is selected.
- After deleting a variable, the next variable is automatically selected.
- If the deleted variable was the last variable in the list of children of its parent, the previous variable is selected instead.
- If the deleted variable was the last remaining child of its parent altogether, the parent is selected instead.
=> XIVY-11980 implement variable delete control

packages/new-editor/src/components/variables/data/variable.test.ts, packages/new-editor/src/components/variables/data/variable.ts, packages/new-editor/src/components/variables/detail/Metadata.tsx
I think this is fine for now but would it make sense to change the value input to a file picker in the future?
I guess this is not so straight-forward to implement.
=> XIVY-11980 implement fileMetadata

packages/variable-editor/src/components/variables/detail/VariablesDetail.tsx
Not sure why but this actually does work and really only takes focus after adding a new variable.
=> XIVY-14079 focus name input of new variable

packages/variable-editor/src/VariableEditor.tsx
"Query data cannot be undefined. Please make sure to return a value other than undefined from your query function. Affected query key: ["validate"]"
=> fix console warning

packages/variable-editor/src/components/variables/master/VariablesMaster.css, packages/variable-editor/src/components/variables/master/VariablesMaster.tsx
When validation messages are present, a horizontal scrollbar appears at the bottom of the table because of the border around the table row. I tried many different approaches like `box-sizing: border-box` and calculating a new width if validation messages are present (`width: calc(100% - 2px)`) but nothing worked. This is the approach I landed on.
Before:
After:
=> XIVY-14003 remove scrollbar if validation messages are present

integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/AddVariableDialog.ts, integrations/standalone/tests/pageobjects/Combobox.ts, integrations/standalone/tests/pageobjects/VariableEditor.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/utils/tree/tree.test.ts, packages/variable-editor/src/utils/tree/tree.ts
when the dialog to add a new variable is opened, the namespace field is filled with
- nothing, if no row is selected
- the key of the selected row, if it has children and therefore is a folder
- the key of the parent row, if it does not have children and therefore is a variable and a parent row exists
- nothing, if it does not have children and therefore is a variable but no parent exists (leaf node on topmost level)
added unittests for the logic mentioned above
added playwright tests for filling the namespace field, including new pageobjects
=> XIVY-14357 fill namespace on add dialog open

integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/Combobox.ts, integrations/standalone/tests/pageobjects/VariableEditor.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/utils/tree/tree.test.ts, packages/variable-editor/src/utils/tree/tree.ts
the name field fill now be automatically filled with 'NewVariable'
if that variable name already exists on the initially selected namespace, an index will be added to the end. e.g. 'NewVariable2', 'NewVariable3', etc.
added unittests for finding the name to fill in and improved playwright test to check for it to be present when opening the add dialog.
=> XIVY-14357 automatically fill name of add dialog

integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/AddVariableDialog.ts, integrations/standalone/tests/pageobjects/Button.ts, integrations/standalone/tests/pageobjects/Combobox.ts, integrations/standalone/tests/pageobjects/FieldsetMessage.ts, package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/utils/tree/tree.test.ts, packages/variable-editor/src/utils/tree/tree.ts
name cannot be empty or already present in the provided namespace
validation updates on changes made to the name input field or the namespace combobox
create button is disabled if any validation messages are present
added unittests and playwright tests including new pageobjects
=> XIVY-14357 validate name in add variable dialog

integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/AddVariableDialog.ts, integrations/standalone/tests/pageobjects/FieldsetMessage.ts, packages/variable-editor/src/components/variables/data/test-utils/types.ts, packages/variable-editor/src/components/variables/data/validation-utils.test.ts, packages/variable-editor/src/components/variables/data/validation-utils.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx
check that the input namespace does not collide with any known variables
=> XIVY-14357 validate namespace field of add dialog

integrations/standalone/tests/mock/variable-editor-detail.spec.ts, integrations/standalone/tests/mock/variable-editor.spec.ts, integrations/standalone/tests/pageobjects/Combobox.ts, integrations/standalone/tests/pageobjects/VariableEditor.ts, packages/variable-editor/src/components/variables/data/variable.ts, packages/variable-editor/src/components/variables/master/AddVariableDialog.tsx, packages/variable-editor/src/utils/tree/test-utils/types.ts, packages/variable-editor/src/utils/tree/tree-data.test.ts, packages/variable-editor/src/utils/tree/tree-data.ts, packages/variable-editor/src/utils/tree/tree.test.ts, packages/variable-editor/src/utils/tree/tree.ts, packages/variable-editor/src/utils/tree/types.ts
variable will now be created where the data of the add dialog suggests
- if the namespace is empty, it will be created on the topmost level
- if the namespace exists already, it will be added to that namespace
- if any or all parts of the namespace do not exist already, they will be created as well
with this, the story is finished
=> XIVY-14357 implement variable creation

packages/variable-editor/src/components/variables/data/test-utils/variables-empty.ts, packages/variable-editor/src/components/variables/data/variable-utils.test.ts, packages/variable-editor/src/components/variables/data/variable-utils.ts
Write an empty string (`""`) instead of `"null"` for a previously missing variable value.
=> XIVY-14795 do not write null for empty values

package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/detail/Value.tsx, packages/variable-editor/src/components/variables/detail/VariablesDetailContent.tsx
Before:
After:
You may ask yourself WTF 🤣 
I was also surprised at the beginning, and I needed some time to find the problem.
The reason is that there are two ways you can write an input field, controlled and uncontrolled:
- controlled: you hold the state -> use the `value` prop
- uncontrolled: the browser holds the state -> use the `defaultValue` prop
So before we used the `value` prop, means we need to hold the state and you may now think we do. I have two assumptions why this is still a problem:
- The reference of the variable changes, so react means there is a new value, and "rerenders to much" of the input so the cursor state forgets where it was
- The parent rerenders and somehow the input losses because of this to much info
And the solution currently for this is:
- Just use the …
=> XIVY-15025 Fix input focus to end jump

packages/variable-editor/src/components/variables/master/VariablesMasterContent.css, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx
Regarding https://github.com/axonivy/dataclass-editor-client/pull/38
I think I found a better approach while doing the same for the variables editor.
We have an element that triggers the desired `onClick` function and takes the whole space of the master content (`master-content-container`). On the first and only child (`master-content`), we stop the propagation of the event. This way, we don't have to stop it on the rows the control buttons and the search field individually.
=> deselect if clicked anywhere in master content

integrations/standalone/src/mock/meta.ts, packages/protocol/src/editor.ts, packages/protocol/src/types.ts, packages/variable-editor/src/components/variables/data/metadata.test.ts, packages/variable-editor/src/components/variables/data/metadata.ts, packages/variable-editor/src/components/variables/data/test-utils/variables-with-metadata.ts, packages/variable-editor/src/components/variables/data/variable-utils.test.ts, packages/variable-editor/src/components/variables/data/variable-utils.ts, packages/variable-editor/src/components/variables/detail/DetailContent.test.ts, packages/variable-editor/src/components/variables/detail/DetailContent.tsx, packages/variable-editor/src/components/variables/detail/Metadata.tsx, packages/variable-editor/src/components/variables/dialog/OverwriteDialog.tsx, packages/variable-editor/src/components/variables/dialog/VariableBrowser.tsx, packages/variable-editor/src/components/variables/dialog/known-variables.test.ts, packages/variable-editor/src/components/variables/dialog/known-variables.ts, playwright/tests/integration/mock/detail.spec.ts, playwright/tests/integration/mock/import.spec.ts, playwright/tests/pageobjects/EnumValues.ts
The endpoint `knownVariables` has been adapted in the core to return the meta data details of variables of type enum (values) and file (extension). These values are now set on the overwriting variable when using the overwrite dialog.
Additionally:
- Added tests for `nodeIcon`.
- Added tests that editing meta data details is disabled on overwriting variables.
- Minor refactors here and there.
=> XIVY-15648 meta data details of known variables

integrations/standalone/package.json, package-lock.json, package.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx, packages/variable-editor/src/utils/tree/tree.ts, playwright/tests/integration/mock/editor.spec.ts, playwright/tests/pageobjects/Table.ts
I have added enhanced keyboard support for the main table in the Variable Editor. You can now perform the following actions:
- Navigate through rows using the arrow up/down keys.
- Expand or collapse child rows using the arrow right/left keys.
- Open the inscription view for a selected row by pressing Enter.
=> Add Navigation via ArrowKey in Main-Table

packages/variable-editor/src/components/variables/master/VariablesMasterContent.css
A little bit is cut
Before:
After:
=> XIVY-15022 Fix overflow

renovate.json
I vote for first only on master until we have a setting which we want for R12.
- Currently renovate also creates PR's for major update etc. which I'm not sure is the right thing for LTS12...
- Also should we first know how we can disable it for some dependencies etc.
=> Disable renovate on R12 branch

packages/variable-editor/src/components/variables/master/VariablesMasterContent.css, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx
When a validation message is present, a border is drawn around the respective table row.
In the Pro Designer, this makes a horizontal scrollbar appear on the table, because the border makes the table no longer fit in its container.
This does not happen in Neo or when running the Editor standalone.
I don't understand why this discrepancy exists, but unsetting `overflow-x` on the table makes the scrollbar no longer appear.
However, the border on the right side will not be visible as it does not fit in the container as mentioned above.
No visual change is made to the Neo integration or the standalone Editor.
=> remove horizontal scrollbar in pro designer > master

packages/variable-editor/src/components/variables/master/VariablesMasterContent.css, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx
When a validation message is present, a border is drawn around the respective table row.
In the Pro Designer, this makes a horizontal scrollbar appear on the table, because the border makes the table no longer fit in its container.
This does not happen in Neo or when running the Editor standalone.
I don't understand why this discrepancy exists, but unsetting `overflow-x` on the table makes the scrollbar no longer appear.
However, the border on the right side will not be visible as it does not fit in the container as mentioned above.
No visual change is made to the Neo integration or the standalone Editor.
=> remove horizontal scrollbar in pro designer > 12

.github/renovate.json
Will use shared config:
https://github.com/axonivy/renovate-config/blob/master/npm.json
- Labels are added in shared preset
- Activating updates on all release branches, but prevent major updates on release branches
- Prevent updating axonivy packages is already defined in shared preset
=> Use shared preset for renovate

package-lock.json, packages/variable-editor/package.json, packages/variable-editor/src/components/variables/master/ValidationRow.css, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.css, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx
- Virtualize rows to improve performance.
- Hard code row height to `36px`.
- Set specific values for sizes in the column defintion because the new layout requires it.
- Fix right side of border on rows with messages not being visible.
Existing problems:
- Did not manage to make table header sticky.
- Because of the new layout, the columns are not automatically using all the available space.
This means that the rightmost column will be cut off even though there seems to be more space available.
And because of our implementation of `TableResizableHeader`, the rightmost row is currently not resizable.
=> XIVY-14462 add row virtualization > 12

packages/variable-editor/src/components/variables/data/variable.ts, packages/variable-editor/src/components/variables/master/ValidationRow.tsx, packages/variable-editor/src/components/variables/master/VariablesMasterContent.test.ts, packages/variable-editor/src/components/variables/master/VariablesMasterContent.tsx
Instantiate the table with a clone of the variables including their validation messages.
Use these validation messages to calculate the height of the virtual rows without the need to use the DOM elements.
Virtualization seems to work a lot better now.
=> XIVY-16068 improve virtual row height calculation > 12

.ivy/raise-deps.sh, .ivy/raise-version.sh, build/integration/Jenkinsfile, package.json
raise-deps should let "workspace:" prefixes and only change the version behind.
Also replace `--frozen-lockfile=false` with `--no-frozen-lockfile`
=> Fix raise-deps with pnpm
